name: BFHelmets
main: com.vark.bfhelmet.Main
version: 0.1
api-version: 1.15
commands:
    wear:
        description: Wear a Helmet!
        usage: /wear

permissions:
    bfhelmet.admin:
        description: Ability to spawn a helmet in
        default: op
   
