name: BFHelmets
main: com.vark.bfhelmet.Main
version: 0.6
api-version: 1.16
commands:
    helmets:
        description: Helmet GUI!
        usage: /helmets

permissions:
    bfhelmet.admin:
        description: Ability to spawn a helmet in
        default: op
   
